### ISSUE TITLE
Post Formats

### ISSUE THREAD

**Issue by danielsale** [morethemesbaby/log-lolla-pro#7]
Where can I find out how to properly use all of the post formats? I remembered "quote" and "cite" from another theme I once used, but am wondering about the others now.

Thanks for the theme!

**Comment by metamn** [comment]
Perhaps this can help: https://morethemes.baby/themes/log-lolla/features/post-formats/

Or WordPress' original documentation: https://developer.wordpress.org/themes/functionality/post-formats/

**Comment by danielsale** [comment]
Thanks!

**Comment by ghost** [comment]
Hi,
I have a problem with Post Format Standard. When I click in this option the page can't be found. You can see it in the images attached below. What can I fix it? Thanks for the theme! I really like it  :-)

![Captura de Pantalla 2021-04-29 a les 18 37 49](https://user-images.githubusercontent.com/83419895/116852762-36396380-abf5-11eb-9dd7-fd82852fb0d8.png)
![Captura de Pantalla 2021-04-29 a les 18 37 27](https://user-images.githubusercontent.com/83419895/116852772-3b96ae00-abf5-11eb-9d90-9145ec0ccbaf.png)

[goodthingsgoodplanet.com](url)

**Comment by metamn** [comment]
Hey @leandraboj 

Thanks for the compliment :)

I no longer maintain this theme due to lack of interest. 

Please feel free to fork the repo and make it your own.

Thanks,
Csongor

**Comment by metamn** [comment]
BTW, the full source code of the pro version can be found here: https://github.com/metamn/log-lolla-pro-theme
